upstreams: 
  - listen_addr: "127.0.0.1:7001"
    url_map:
      - src_paths:
          - "/api/v1/label/[^/]+/values"
        url_prefix:
          - "http://127.0.0.1:7010/api"
          - "http://127.0.0.1:7011/api"
        users:
          - username: "admin"
            password: "d033e22ae348aeb5660fc2140aec35850c4da997"

  - listen_addr: 127.0.0.1:7002
    url_map:
      - src_paths:
          - "/test"

  - listen_addr: 127.0.0.1:7023
    
  - listen_addr: 127.0.0.1:7024